### PR TITLE
Add targets to avoid ARCH_ALL payload confusion

### PR DESCRIPTION
**Pull request by wvu**
#6421

### CODE REVIEW

**Comment by joevennix** [comment]
Can you add X86_64 and MIPSLE as well

**Comment by joevennix** [comment]
Oh wait you totally got MIPSLE

**Comment by wvu** [comment]
Derp on x64. :)

**Comment by wvu** [comment]
Going off https://developer.android.com/ndk/guides/arch.html.

**Comment by joevennix** [comment]
Looks good, thanks for figuring that out!

**Pull request merged**
